name: main
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Setup Git
        run: |
          git config --local user.name "kettanaito"
          git config --local user.email "kettanaito@gmail.com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Tests
        run: yarn test

      - name: Build
        if: github.ref != 'refs/heads/main'
        run: yarn build

      - name: Release
        if: github.ref == 'refs/heads/main'
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
